# Generated by Django 5.2.7 on 2026-01-13 02:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('hmac_level', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('hmac_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=app.models.default_created_at)),
                ('hmac_created_at', models.CharField(blank=True, max_length=500)),
                ('record_size', models.IntegerField(default=0)),
                ('hmac_record_size', models.CharField(blank=True, max_length=500)),
                ('user_identity', models.EmailField(max_length=254)),
                ('hmac_user_identity', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Log Entry',
            },
        ),
    ]
