# Generated by Django 5.2.7 on 2026-01-18 01:31

import logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='action',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='logentry',
            name='client_sign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='current_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='logentry',
            name='hmac_action',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='logentry',
            name='hmac_ip_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='logentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='previous_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='created_at',
            field=models.DateTimeField(default=logs.models.default_created_at),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=models.TextField(),
        ),
    ]
