# Generated by Django 5.2.7 on 2026-01-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logentry_action_logentry_client_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
