"""
Django settings for health project.

Generated by 'django-admin startproject' using Django 3.0.4.

Django,
SMTPLIB,
Hashlib,

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv("credentials.env")

# -----------------------------------------------------------------------------
# PKI (Certificate-based authentication)
# These paths are used by app.pki.check_ca.verify_doctor_certificate
# -----------------------------------------------------------------------------

PKI_DIR = Path(BASE_DIR) / "pki"
TRUSTED_ROOT_CA = PKI_DIR / "root_ca" / "root_ca.crt"
TRUSTED_ORG_CA_DIR = PKI_DIR / "org_ca"

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
STATICFILES_DIRS = ['static']
MEDIA_ROOT = os.path.join(BASE_DIR, 'user_data')
MEDIA_URL = '/user_data/'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'health.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'health.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'health_db',           
        'USER': 'health_user',        
        'PASSWORD': 'your_secure_password', 
        'HOST': 'localhost',           
        'PORT': '5433',
    }, 
    'logs': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'logs_db',           
        'USER': 'logs_user',        
        'PASSWORD': 'your_secure_password', 
        'HOST': 'localhost',           
        'PORT': '5434',
    }, 
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SECURE = False         # Localhost-friendly for development
SESSION_COOKIE_HTTPONLY = False       # For debugging in browser
SESSION_COOKIE_SAMESITE = 'Lax'       # Allows cross-origin requests from localhost
SESSION_COOKIE_AGE = 10 * 60  # 10 minutes
SESSION_SAVE_EVERY_REQUEST = True     # Refresh session on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('APP_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
ALERT_RECIEVER_EMAIL = 'typeanaddresshere@gmail.com'

DATABASE_ROUTERS = ['health.routers.LogRouter']
HMAC_KEY = os.getenv('HMAC_KEY')