# Generated by Django 5.2.7 on 2026-01-18 11:39

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='cert_not_after',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='cert_not_before',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hmac_certificate',
        ),
        migrations.AlterField(
            model_name='notification',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='app.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='shared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shared'),
        ),
        migrations.AlterField(
            model_name='shared',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='shared',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.folder'),
        ),
        migrations.CreateModel(
            name='File_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('signed_title', models.CharField(max_length=500)),
                ('signed_blob', models.CharField(max_length=500)),
                ('blob_url', models.CharField(max_length=500)),
                ('hmac_blob_url', models.CharField(blank=True, max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('signed_size', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=app.models.default_created_at)),
                ('hmac_created_at', models.CharField(blank=True, max_length=500)),
                ('record_size', models.IntegerField(default=0)),
                ('hmac_record_size', models.CharField(blank=True, max_length=500)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.folder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='app.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='File_versions',
        ),
    ]
