# Generated by Django 5.2.7 on 2026-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_doctor_cert_not_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hmac_certificate',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='cert_not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='cert_not_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
